name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, '*']

    env:
      WASI_VERSION: 14
      WASI_SDK_PATH: /tmp/wasi-sdk

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install test dependencies
        run: |
          sudo apt install xz-utils brotli

      - name: Set up WASI-SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_VERSION}/wasi-sdk-${WASI_VERSION}.0-linux.tar.gz
          mkdir -p $WASI_SDK_PATH
          tar xvf wasi-sdk-*-linux.tar.gz -C $WASI_SDK_PATH --strip-components=1

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Build & test
        run: wasisdkroot=$WASI_SDK_PATH make
        env:
          # Legacy provider required for old webpack version in new Node releases:
          NODE_OPTIONS: ${{ matrix.node-version != '16.x' && '--openssl-legacy-provider' || '' }}